---
- hosts: all
  become: yes
  become_user: root
  gather_facts: true
  tasks:
    - name: Spin up a container
      docker_container:
        state: started
        image: nginx:latest
        restart: yes
        name: "nginx"
        env:
           mysql: "mysql-h localhost:3399"
        exposed_ports:
          - 80
        volumes:
          - /home/ubuntu/docker/  
        env_file: /home/ubuntu/docker/dev.env  
        
   
